spring:
  application:
    name: santander-dev-week-2024
  datasource:
    url: jdbc:h2:mem:sdw2024
    driver-class-name: org.h2.Driver
    username: sa
    poassword: '' 
  h2:
    console:
      enabled: true # Dá uma interface visual para interagir com o BD
